version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: arvyax_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - arvyax_net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: arvyax_server
    restart: unless-stopped
    env_file: ./server/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/arvyax-journal
      - CLIENT_URL=http://localhost
    depends_on:
      - mongo
    networks:
      - arvyax_net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: arvyax_client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - arvyax_net

volumes:
  mongo_data:

networks:
  arvyax_net:
